<?php if (count($articles)): ?>
    <?php foreach ($articles as $article): ?>
        <article>
            <h2><?=$this->escape($article->title)?></h2>
            <section class="short-desc">
                <?=$this->escape($article->shortDescription)?>
            </section>
            <section class="meta">
                <?php if (count($article->authors)): $counter = 1;?>
                    <i class="glyphicon glyphicon-user"></i>
                    <?php foreach ($article->authors as $author): ?>
                        <a href="<?=$this->baseUrl()?>/author/<?=$author->authorId?>"><?=$this->escape($author->firstName) . ' ' . $this->escape($author->lastName)?></a><?php if ($counter != count($article->authors)) { echo ','; $counter++; } ?>
                    <?php endforeach; ?>
                <?php endif; ?> |

                <?php if ($article->category): ?>
                    <i class="glyphicon glyphicon-folder-close"></i>
                    <a href="<?=$this->baseUrl()?>/category/<?=$article->category->categoryId?>"><?=$this->escape($article->category->name)?></a> |
                <?php endif; ?>

                <?php if (count($article->tags)): $counter = 1;?>
                    <i class="glyphicon glyphicon-tag"></i>
                    <?php foreach ($article->tags as $tag): ?>
                    <a href="<?=$this->baseUrl()?>/tag/<?=$tag->tagId?>"><?=$this->escape($tag->tagName)?><?php if ($counter != count($article->tags)) { echo ','; $counter++; } ?></a>
                    <?php endforeach; ?>
                <?php endif; ?>
            </section>
            <div>
                <a class="btn btn-success" href="<?=$this->baseUrl()?>/article/<?=$article->articleId?>">Read</a>
            </div>
            <?php if ($article->price == 0): ?>
                <div class="remark free">FREE for logged!</div>
            <?php elseif ($this->isLoggedUser() && $this->isArticlePurchasedByUser($article->articleId, $this->getUser()->userId)):  ?>
                <div class="remark purchased">In collection</div>
            <?php endif; ?>
        </article>
    <?php endforeach; ?>
<?php else: ?>
    <p>There are no articles.</p>
<?php endif; ?>