<article style="border: none;">
    <h2><?=$this->escape($article->title)?></h2>

    <?php if (($this->isLoggedUser() && $isFreeArticle) || (!$isFreeArticle && $article->isPurchased)): ?>
    <section class="content">
        <?=$this->escape($article->content)?>
    </section>
    <?php else: ?>
    <section class="short-desc">
        <?=$this->escape($article->shortDescription)?>

        <?php if ($isFreeArticle): ?>
        <div class="panel panel-warning" style="margin-top: 20px;">
            <div class="panel-body">
                If you want to read more please <a href="<?=$this->baseUrl()?>/login">Log in</a>
            </div>
        </div>
        <?php else: ?>
            <div class="panel panel-warning" style="margin-top: 20px;">
                <div class="panel-body">
                    If you want to read more please buy the article.
                    <a
                        class="btn btn-success pull-right"
                        <?php if ($this->isLoggedUser()): ?>onclick="if (!confirm('You will be charged for $<?=$article->price?>. Dou you confirm the purchase?')) return false;"<?php endif; ?>
                        href="<?=$this->baseUrl()?>/user/buy/<?=$article->articleId?>">Buy $<?=$article->price?>
                    </a>
                </div>
            </div>

        <?php endif; ?>

    </section>
    <?php endif; ?>

    <section class="meta">
        <?php if (count($article->authors)): $counter = 1;?>
            <i class="glyphicon glyphicon-user"></i>
            <?php foreach ($article->authors as $author): ?>
                <a href="<?=$this->baseUrl()?>/author/<?=$author->authorId?>"><?=$this->escape($author->firstName) . ' ' . $this->escape($author->lastName)?></a><?php if ($counter != count($article->authors)) { echo ','; $counter++; } ?>
            <?php endforeach; ?>
        <?php endif; ?> |

        <?php if (!empty($article->category)): ?>
            <i class="glyphicon glyphicon-folder-close"></i>
            <a href="<?=$this->baseUrl()?>/category/<?=$article->category->categoryId?>"><?=$this->escape($article->category->name)?></a> |
        <?php endif; ?>

        <?php if (count($article->tags)): $counter = 1;?>
            <i class="glyphicon glyphicon-tag"></i>
            <?php foreach ($article->tags as $tag): ?>
                <a href="<?=$this->baseUrl()?>/tag/<?=$tag->tagId?>"><?=$this->escape($tag->tagName)?></a><?php if ($counter != count($article->tags)) { echo ','; $counter++; } ?>
            <?php endforeach; ?>
        <?php endif; ?>
    </section>

    <h3>Comments</h3>

    <?php if ($this->isLoggeduser()): ?>
    <div class="panel panel-info">
        <div class="panel-body">
            <form class="form" action="<?=$this->baseUrl()?>/comment/new" id="comment-form" method="post">
                <input type="hidden" name="user_id" value="<?=$this->getUser()->userId?>" />
                <input type="hidden" name="article_id" value="<?=$article->articleId?>" />
                <div class="form-group">
                    <label for="message">Add your comment</label>
                    <textarea class="form form-control" name="message" id="message" cols="30" rows="7"></textarea>
                </div>
                <div class="form-group">
                    <button type="submit" id="submit" name="submit" class="btn-default btn">Send</button>
                </div>
            </form>
        </div>
    </div>
    <?php endif; ?>

    <div id="comments-list">
    <?php if (0 !== count($comments)): ?>
        <?php foreach($comments as $comment): ?>
        <div class="panel panel-info">
            <div class="panel-body"><?=$comment->text?></div>
            <div class="panel-footer">
                <strong><?=$comment->getUser()->username?></strong>, <?=$comment->date?>
            </div>
        </div>
        <?php endforeach; ?>
    <?php else: ?>
    <p>There are no comments yet.</p>
    <?php endif; ?>
    </div>
</article>

<script>
    $(document).ready(function() {
        insertLoadMoreLink(<?=$commentsCount?>);

        var commentTemplate = '<div class="panel panel-info">\
                                    <div class="panel-body">{message}</div>\
                                    <div class="panel-footer">\
                                        <strong>{username}</strong>, {date}\
                                    </div>\
                                </div>';

        $('#submit').on('click', '', [], function(e) {
            e.preventDefault();

            var form = $('#comment-form');
            $.post(
                form.attr('action'),
                form.serialize(),
                function(data) {
                    if (data.success == 0) {
                        alert(data.message);
                    } else if (data.success == 1) {
                        $('#comment-form textarea').val('');
                        var comment = createCommentFromTemplate(data.comment.message, data.comment.username, data.comment.date);

                        if ($('#comments-list div').length == 0) {
                            $('#comments-list').html('');
                        }

                        $(comment).prependTo($('#comments-list'));

                        alert('Comment was saved!');
                    }
                },
                'json'
            );
        });

        $('#load-more').on('click', '', [], function() {
            var comments = $('#comments-list > div');
            var loader = $('#comment-loader');
            loader.show();

            $.post(
                '<?=$this->baseUrl()?>/comment/load',
                {
                    article : <?=$article->articleId?>,
                    start : comments.length
                },
                function(data) {
                    for(var i = 0; i < data.comments.length; i++) {
                        var comment = createCommentFromTemplate(
                            data.comments[i].text,
                            data.comments[i].user,
                            data.comments[i].date
                        );
                        $('#comments-list').append(comment);
                    }
                    loader.hide();
                },
                'json'
            );

        });

        function createCommentFromTemplate(message, username, date) {
            return commentTemplate
                .replace('{message}', message)
                .replace('{username}', username)
                .replace('{date}', date);
        }

        function insertLoadMoreLink(countComments) {
            if (countComments > 10) {
                var loadMoreContent = '<p id="comment-loader" style="text-align:center; display: none;"><img src="<?=$this->baseUrl()?>/assets/img/comment-loader.gif" alt="Loading ..."></p> <p><a href="javascript:void(0)" id="load-more">Load more</a></p>';

                $(loadMoreContent).insertAfter($('#comments-list'));
            }
        }

    });
</script>