<?php if ($pagination['countAll']): ?>
    <?php foreach ($pagination['data'] as $article): ?>
        <article>
            <h2><?=$this->escape($article->title)?></h2>
            <section class="short-desc">
                <?=$this->escape($article->shortDescription)?>
            </section>
            <section class="meta">
                <?php if (count($article->authors)): $counter = 1;?>
                    <i class="glyphicon glyphicon-user"></i>
                    <?php foreach ($article->authors as $author): ?>
                        <a href="<?=$this->baseUrl()?>/author/<?=$author->authorId?>"><?=$this->escape($author->firstName) . ' ' . $this->escape($author->lastName)?></a><?php if ($counter != count($article->authors)) { echo ','; $counter++; } ?>
                    <?php endforeach; ?>
                <?php endif; ?> |

                <?php if (!empty($article->category)): ?>
                    <i class="glyphicon glyphicon-folder-close"></i>
                    <a href="<?=$this->baseUrl()?>/category/<?=$article->category->categoryId?>"><?=$this->escape($article->category->name)?></a> |
                <?php endif; ?>

                <?php if (count($article->tags)): $counter = 1;?>
                    <i class="glyphicon glyphicon-tag"></i>
                    <?php foreach ($article->tags as $tag): ?>
                        <?=$this->escape($tag->tagName)?><?php if ($counter != count($article->tags)) { echo ','; $counter++; } ?>
                    <?php endforeach; ?>
                <?php endif; ?>
            </section>
            <div>
                <a class="btn btn-success" href="<?=$this->baseUrl()?>/article/<?=$article->articleId?>">Read</a>
            </div>
            <?php if ($article->price == 0): ?>
                <div class="remark free">FREE for logged!</div>
            <?php elseif ($isLoggedUser && $article->isPurchased):  ?>
                <div class="remark purchased">In collection</div>
            <?php endif; ?>
        </article>
    <?php endforeach; ?>

    <?php if ($pagination['countPages'] > 1): ?>
    <nav class="paginaton">
        <?php if ($pagination['prev']): ?>
        <a class="btn btn-default pull-left" href="?page=<?=$pagination['prev']?>">&laquo; Prev</a>
        <?php endif; ?>

        <?php if ($pagination['next']): ?>
        <a class="btn btn-default pull-right" href="?page=<?=$pagination['next']?>">Next &raquo;</a>
        <?php endif; ?>
        <div class="clearfix"></div>
    </nav>
    <?php endif; ?>

<?php else: ?>
    <p>There are no articles.</p>
<?php endif; ?>