<?php if (!empty($error)): ?>
<div class="alert alert-danger alert-dismissable" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>Error!</strong> <?=$error?>
</div>
<?php endif; ?>
<form class="form-horizontal login" method="post" action="<?=$this->baseUrl()?>/login">
    <div class="form-group">
        <label for="username" class="col-sm-2 control-label">Username</label>
        <div class="col-sm-10">
            <input type="text" class="form-control" id="username" name="username" placeholder="Username" value="<?=$username?>">
        </div>
    </div>
    <div class="form-group">
        <label for="password" class="col-sm-2 control-label">Password</label>
        <div class="col-sm-10">
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Sign in</button>
        </div>
    </div>
</form>

<div class="alert alert-warning">
    <strong>Login:</strong> test-user1, <strong>Password:</strong> test-user1<br/>
    <strong>Login:</strong> test-user2, <strong>Password:</strong> test-user2<br/>
</div>